### ISSUE TITLE
Error using the images after exported to computer from lobe dataset

### ISSUE THREAD

**Issue by rachelc8997** [lobe/image-tools#7]
I used this tool to sort my lobe database into folders on my computer. This part works well, and I can see the images in their proper folders.

When I try to use those image files that I exported, they are corrupt. The file opens properly using Photos on Windows, but I've tried opening the images in Matlab or Python and both are saying the images are corrupt and cannot be read. Just wondering if there is something going on in the saving process?

In Python the error is: 
**UnidentifiedImageError: cannot identify image file 'C:\\Users\\Rachel\\Documents\\MASTERS\\Pilot Data Collection\\Lobe internet\\test set\\Null\\drink\\056b91ae69c0268cb41b3acde863494884e38ef3e5c2b68a00166ca46c241a8e.jpg'**
 
When I try to open any other image on my computer (not exported with this tool) with the same code, it works. 
I think it might be a permissions issue? But I have tried to run everything as an Administrator. 

thanks so much, its a great tool otherwise!

**Comment by mbeissinger** [comment]
The export dataset from lobe function is using shutil.copyfile from our stored blob, and making it a jpg (https://github.com/lobe/image-tools/blob/master/dataset/export_from_lobe.py#L103). What were your original file types?

Are you using Python from a virtual environment? I'd highly recommend it to make sure everything is clean (https://docs.python.org/3/tutorial/venv.html). You shouldn't have to run anything here as administrator. Were you running Lobe as admin?

**Comment by mbeissinger** [comment]
@rachelc8997 can you try doing the export from the GUI app rather than running from the command line? Are you able to open the exported image files then?

**Comment by rachelc8997** [comment]
I solved it. 
I just deleted and reinstalled Python and the image-tools (I noticed there was a new version on gitlab) and it is now working with Python with pillow. 

It still has an issue reading the image in Matlab (using both the GUI and using python to export)

**Comment by berbschloe** [comment]
I think the image is getting exported a WEBP even though the file extension is '.jpg'?
Look at the file info in the Preview App on Mac.

![Screen Shot 2021-02-12 at 2 37 13 PM](https://user-images.githubusercontent.com/5903560/107820283-26218e80-6d40-11eb-8a82-e9aae3da07f7.png)

Also I get a encoding error when trying to decode the image file into a tensor in nodejs.
`Expected image (JPEG, PNG, or GIF), got unknown format starting with 'RIFF\330j\000\000WEBPVP8X`

Right now I'm trying to decode the image file as a WEBP in node.

**Comment by mbeissinger** [comment]
Interesting, is that image originally WebP? I should probably make it check (we strip the extension) instead of just making it jpg.

**Comment by berbschloe** [comment]
The image was taken via the web camera from in Lobe application (Mac).

**Comment by mbeissinger** [comment]
@berbschloe should be fixed now! Saving the images with Pillow using their existing file format vs using the shutil.copy and adding the .jpg
